apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hireai
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - hpa.yaml
  - ingress.yaml
# secret.yaml is created by hand (see secret.example.yaml); migrate-job.yaml is applied separately.
